### ISSUE TITLE
网页没内容

### ISSUE THREAD

**Issue by skaaadiii** [odex21/ArknightsData#12]
yarn start之后打开网页能显示名称，但是没有内容，sass已经安装，theme也解压了。

**Comment by odex21** [comment]
修改下  src/utils/listVer.js 里的索引
···
// ?处理数据的脚本涉及服务器账号，也就GameData那个文件夹，所以，这里提供一个11.19日版本的列表。
const charListVer = char //7120440414751
const stageListVer = stage //6076469254751
const enemyListVer = enemy //1574138107584
