### ISSUE TITLE
关于危机合约关卡数据

### ISSUE THREAD

**Issue by sxyugao** [odex21/ArknightsData#13]
危机合约的中转站的路线是错误的，还有大部分危机合约关卡介绍也是错误的

（话说项目介绍里的链接要不要换一下

**Comment by odex21** [comment]
应该修正了

**Comment by sxyugao** [comment]
危机合约的中转站的路线问题还没有修正

**Comment by odex21** [comment]
那个周末，首页好像有说？
应该是跟摆箱子一起改

**Comment by sxyugao** [comment]
首页只说了H6-2，所以不知道。。那我关了吧
