### ISSUE TITLE
关于卡特亚的事

### ISSUE THREAD

**Issue by sxyugao** [odex21/ArknightsData#16]

**Comment by MonianHello** [comment]
在Is问不太好吧

**Comment by sxyugao** [comment]
@MonianHello  自己给自己 downvote 可不好吧，不会想给我扣帽子吧。我可是全删了还 close 了。

**Comment by odex21** [comment]
你以为他的商务qq不是中间人吗。
他商务qq就是，欧拉的管理组里的，两个闺蜜轮班的。

我发的截图，都是欧拉的人给我的。
欧拉的人还不知道我qq吗。
我找商务qq不还是中间人。

到底谁，要把事情搞大，两天不上班，疯狂直播骂我?

**Comment by MonianHello** [comment]
> @MonianHello 自己给自己 downvote 可不好吧，不会想给我扣帽子吧。我可是全删了还 close 了。

没看到，抱歉

**Comment by sxyugao** [comment]
@MonianHello 没事，我回复你的时候心情有点不好，主要是 NGA 那边的言论看得我很生气，可能会把一些那里的风气带过来一些，显得有点阴阳怪气

**Comment by sxyugao** [comment]
@odex21 你是不是当开发太久了，都不知道二次元手游圈的风气了
