### ISSUE TITLE
备份数据

### ISSUE THREAD

**Issue by winrey** [odex21/ArknightsData#17]
[backup.zip](https://github.com/odex21/ArknightsData/files/4428680/backup.zip)
这是那栋高楼的爬下来的备份数据，以防被删/锁后再出什么问题无从查证。
但愿永远不要有机会用到。

GBK编码打开。

**Comment by winrey** [comment]
站长保存住之后记得close了，还有需要我可以删掉上面的备份文件。

**Comment by winrey** [comment]
？？这是失眠了？
不容易，辛苦了

**Comment by odex21** [comment]
又通了个很长的电话， 把贴吧、知乎、nga都都大致看了遍。
他大概是要签约了。

**Comment by winrey** [comment]
我看了您的对线直播。。这里也是写前端的[del]还都是社畜[/del]。。所以真心能理解您的逻辑和每个举动。
对面到底是不是真心觉得你在搞事，其实都能解释。
如果他是真心的，那我只能说太遗憾了………………不过他和他的粉丝开心就好，这事不是GE也至少是TE了。
如果他是装傻，而且高估了他承认错误的代价，那他就绝对不可能承认自己有问题。因为他的粉丝已经先入为主了，从弹幕就能看出来（不过真的有那么多韭菜吗……怀疑是请的水军吧？）。
不过也有可能两种情况都占一半。毕竟人是复杂的。
我怎么都感觉您看出他后期第二种情况偏多，让了他一马呢………………
您也别再这里公开回复我了，就当翻过篇去算了，别影响您生活太多【叹

**Comment by winrey** [comment]
另外我在其他地方（知乎+NGA）说了一些担心会影响您开发动力的偏激的话，这里也顺道给您道个歉然后解释下。

大部分舟游玩家，已经泥潭里的玩家都是明事理支持您的，大学生起步，大部分都是工作党，他们都是可爱且值得我们付出的人。

至于B站直播间的粉丝，也可能有一部分只是行事过激，冲动且缺乏独立判断力的孩子。总会有长大的一天的。

最后向您致敬。

**Comment by winrey** [comment]
另外。
```python
# 同目录建一个叫backup的文件夹
import requests
import time

cookie = "这里放Cookie"
start_page = 1
end_page = 691
sleep_time = 2
headers = {'Cookie': cookie}

def save_page(page):
    url = "https://bbs.nga.cn/read.php?tid=21093526&_ff=-34587507&page=" + str(page)
    res = requests.get(url, headers=headers)
    content = res.content
    # content = content.decode("gbk")
    with open("backup/" + str(page) + ".html", mode='wb') as file:
        file.write(content)

for i in range(start_page, end_page + 1):
    save_page(i)
    time.sleep(sleep_time)
    print("Finish", i)

```

**Comment by sxyugao** [comment]
之所以在 Github 上谈是因为我相信在这还是能理性的看待这件事的。

其实稍微把各个背景都理一下，很多事情都说得通，就是事至如今已经很难挽回了。

首先，看一下人物背景：

您：程序员，开发网站

卡特亚：一个规模算的上比较大的主播，一直被人带节奏，喜欢硬刚到底

内鬼：**最最坏的人，唯恐天下不乱**

稍微理一下事情脉络：

最初：

您搭建资料站，自费服务器支出，但因欧拉资料站引流导致开支超出预计，希望能向卡特亚一方寻求资金帮助，这时内鬼跳出来帮您，您就放心的交给内鬼去办。

结果：内鬼两边点火，双方都不明事情真相，欧拉资料站的人认为您不怀好意，您认为卡特亚那边的人盛气凌人。**这个是后面一切事情的大前提。**

导火索：

4月1日，在内鬼的怂恿下，您发 NGA 帖子“挂”卡特亚。**注意，我这里的“挂”打了引号，因为您可能认为没写出卡特亚本人的昵称，但“直播总是发 648”的方舟主播在 NGA 不会有人不知道这是卡特亚。** 这个时候，事态就开始走向不可逆转的地步。在 NGA，黑卡特亚可以算得上是某种风气，您听信了内鬼的一面之词发出来的帖子，可是把**某些网友**高兴坏了。

事情发酵：

建议去看看原帖下面的回复，在您错误的信息（指主播一点商量意愿都没有，主播很霸道）下一口一个**卡大佐**，再一口一个**卡孝子**，甚至还有的人说关注是**70万阴兵**。您说的卡特亚的水军我是没看见（也可能是我对 NGA 关注不够，如果有证据还是能接受的）。卡特亚本人出面，于4月2日中午开直播澄清（这也是我了解到这次事件的原因）。4月2日晚公布了部分截图，并请您公开谈论，却被您拒绝，您要求私聊。4月3日白天我并没有关注，所以不了解，根据4月3日晚上的直播来看似乎被人忽悠开源项目和黑产有关了。最后4月3日晚双方公开连线。

**在我看来**，您主要做错了2件事，而这2大错误主要归结于您**没有意识到主播和您的区别**：

- 最开始听信内鬼挂人**最最大的错误**

因为卡特亚不是那种如果你和他**诚心谈论**他还给你摆架子的人，如果您一开始不挂人，这件事极大概率是圆满解决的——您拿到服务器费用，得到合作。您的帖子一开始是陈述事实，后半段在您自己眼中可能是吐槽，但在 NGA 的舆论发酵下，完全变味了，所以我在上一个 issue 里提到过建议不通过中间人。卡特亚不得不面对舆论的压力，正如人物背景所描述的那样，卡特亚本人也是苦于各种节奏。而不正确的舆论从何而来？帖子是您发的。**因此一个经常被带节奏的人，您让他去相信您是清白的，这不现实**。所以，**在我看来**， @winrey ，这不是什么阴谋论，只是一个被经常锤的人的合理推测。他建立在对方是恶意的前提之下，而且逻辑完全通顺。舆论已经被带起来了，还是一边倒的。那么这个事就不可能私聊解决，私聊只会给卡特亚留下黑点。所以我说您没有意识到一个主播的难处。否则不会说出“这个帖子发出来以后私聊解决就不会闹大”的话。

- 4月2日晚上没有连线，一直拖到4月3日

真的真的，我是第一批 star 这个项目的人，也一直关注这个项目，提了很多 issue。但是因为4月2日晚上您不肯出面，我甚至取消了这个 star，我真的觉得很遗憾，现在也很后悔。当时取消的原因很简单，聊天记录都放出来了，全是对您不利的截图。语气都很不友好，像“卡秃”“别想跑”。我完全可以理解可能您只是当玩笑话在和内鬼说，但在截图放出来后却一直不肯正面回应，而是一直强调想私聊。你知道这一行为有多令他人怀疑吗？（原谅我用了反问语气，因为我这实在不能克制）我那时候都对您很失望了！这也是我说您不了解主播的原因，**一个大主播，是不可能在公众直播前公布您的个人信息的，否则是自寻死路**。在我看来，如果那天晚上直接连线，越早解除误会对双方就越好，这样后面巅峰也不会被扯进来，事态也不会继续扩大。

而卡特亚的错误是**错误的估计了您**，以前被充满恶意的人锤多了，不相信人心的美好，加上内鬼完美的时间点，说真的，**如果以您是个社会人作为前提，卡特亚的推论完全有理有据**。而且您又先挂了人，心中的推测等于是一下子被证实了一般，因为他实在是被这样带节奏带太多了。

这件事最开始本来卡特亚就不违法，转载也说明了出处，**最多于人情上说不过去**。最开始直播也是围绕没有不允许商用转载自我辩护的，不知道什么时候被人忽悠成了开源项目是黑产。**而按他的人品，如果不闹这么大相信他会很乐意给您补偿的。** 但是，如果一个人，上来就对你说“请捐款”，谁又会高兴呢。卡特亚一直是把您当作一个站长来看待的，也就是一个会公关的人，而据我的了解，大部分站长都是千方百计的为自己站引流。所以他自己会脑补很多东西，我也相信您知道一些 SEO 的东西。但另一方您却只是想做一个资料站。

所以我的总结是：**他是一个主播，不了解开源项目的艰难，会把他那里的公关思维给带进来，把您看成了一个大对手；而您是一个程序员，也不明白主播舆论的重要性，没有仔细斟酌发了挂人帖**

这件事，卡特亚亏了，您也亏了，唯一不亏的也就只剩内鬼了。内鬼的确该死。毕竟工作里项目上线，bug 修完就行，同事们都直来直去，谁会这么心怀鬼胎。而您，在昨天的直播中也承认觉得他是后端便觉得代沟小了很多。

昨晚看直播感觉您还有一些问题没看明白，以上是自己的一些拙见，码字码了很多，希望您能看到。

**Comment by winrey** [comment]
@sxyugao 我认为您被他带节奏了。。我不针对您和卡卡，我只是客观的也摆一些事实和道理。

首先关于违法的事情。如果我们谈法律。那就不能用“我觉得”和“我认为”。

> 《信息网络传播保护条例》第2条规定：“权利人享有的信息网络传播权受著作权法和本条例保护。除法律、行政法规另有规定的外，任何组织或者个人将他人的**作品**、表演、录音录像制品通过信息网络向公众提供，**应当取得权利人许可，并支付报酬**。

欧拉资料站在当时引用的时候就应该询问站长的意见，无论站长是否注明禁止这种行为。

更何况微信公众号菜单是一个“功能”，不会显示原网址，而且确实造成CDN的开销，也就是经济损失。

卡特亚很聪明，他第一时间承认了这个是自己的过失，所以站长不想追究了而已。而在这里站长就上了卡特亚的套——这次直播的大部分时间，都在讨论站长的“过失”。这给了大家一个错误的印象——好像站长是这个事情的主要责任一样。实际上站长只占两成。

某公司的员工代表公司给其它人造成了损失，老板和公司法人需要承担责任吗？

团队成员没有办法第一时间把事情通知上报，导致问题，老板有管理过失吗？

需要，有。但是因为卡卡的快速道歉，站长也不追究，就把他搞得不是这次事件的主要责任人一样。

站长的正确做法，其实是私信发一封24小时撤销的通知函，然后再无此事，至于卡特亚能不能看到，只要通知方法符合一般大众的常识，站长就不需要再管了。期限内不撤销直接一个微信公众号举报。**欧拉就直接没了，而且欧拉的主体也会上微信的黑名单**。

但是站长比较善良，不想公事公办，想促成更好的结局，所以才有了之后的所有事。

而且另说，站长在交涉失败后，只是去NGA未明确指明地吐槽了下，而不是找微信拿截图举报，已经很厚道了。

卡特亚不相信站长的为人。这可以，没有任何问题，但这并不代表你能在公众面前说出来。在没有明确证据的情况下，卡特亚在B站直播这个公共平台，宣传自己“被讹了”，“对面是个高手”（真正的高手应有的行为我上面提过了）。这是什么？往严重说，这是**诽谤污蔑**，可以收律师函的那种。

站长挂他发的是明确的、有证据的事实吧？而他连续两天直播说了站长什么，证据是什么？别告诉我证据是他一直多次想提的某攻略组。

那么这种诽谤污蔑造成了什么样的影响？

首先，站长的个人生活收到打扰。其次，kkdy的名誉权收到了侵犯。不但有人要声称举报kkdy，还有人在特推追着日文推宣传kkdy的不利言论。你不觉得这俩事有一种既视感吗？其实就算是xz他也不想粉丝这么做得，只是到了那个程度他也无力阻止了。

那么对于科特亚，他这次直播只有一个目的：

**让站长承认是在讹他。 请注意，不是要求站长为挂他道歉，而是为讹他道歉。**

跟别提站长究竟需不需要跟他道歉这件事本身还需要讨论了。

其实我本来是也是他的粉丝来着。。现在已经取关了。<del>他推荐的T0危机合约技能我拉了全没用上</del>

**Comment by winrey** [comment]
另外道个歉，我在数据脱敏的时候操作失误，导致锟斤拷了……

代码本身是没问题的。我重新脱敏后又上传了一份，麻烦站长重新保存一下吧 @odex21 

[backup.zip](https://github.com/odex21/ArknightsData/files/4430912/backup.zip)

**Comment by winrey** [comment]
顺带想和您分享点私货 @sxyugao 

## 你知道吗，人很难接受是自己预判立场的错误。卡特亚的粉丝第一次收到卡特亚的单方面的鼓动，很难认为站长真的是清白的。甚至我作为来自NGA的，我在没有看到站长公布的完整记录前，我的观点是“各打50大板”。我也不是什么圣人，我如果从卡特亚知道的这个事，我也会想你一样被节奏带跑；而如果我不是开发者，我也不会能体会到站长的所思所想。我在看聊天记录的时候，就是在找茬。我就是希望找到证据让我自己相信，站长也应该“挨50大板”。而实际上，我看完了记录，我的理性告诉我，不管有多不愿意承认，我之前的立场确实是错的。

卡特亚为什么不能相信站长，因为如果相信站长会让他收到自己内心道德和舆论的双重谴责，毕竟他在线黑了站长两天。我认为他内心是个善良、易情绪化、而且要面子的人。正是这种善良推动着他的潜意识不愿意相信自己的错误。至于他自己声称的什么“主播的教训”，都是他的意识给他潜意识做得掩饰。毕竟，他上次实打实的抄了朋友的打法，而且没有贴出链接，但是现在他凉了么？

而且即使是对双方都有信任和爱护，而且在群体中比较理性的你，也一样被先入为主的看法影响。我很难想象其它粉丝会对站长有什么想法。

这个世界，理应不应该让好人心寒。但是世界根本不是这么运作的。如果换成摊上这事的是我，我没有站长那么好的心理素质，很可能已经躺平任锤了。所以我唯一能做的就是去再也不参与这种事。

**Comment by sxyugao** [comment]
@winrey 对于著作权，没有仔细考据过，我个人是用转载博客文章的原则来评断的，是我的不对。但是，**您认为卡特亚让站长承认是在讹他我是不认同的**。

我也说了，4月2日直播的时候站长没有当面出声也是很大的问题。如果您看过卡特亚放出来的截图，就知道截图完全对站长不利，**两个人提到“要不要挂他”“别想跑”“卡秃”** 这类词汇，你觉得他们会心怀好意吗？这就是证据，并且完全能够支撑卡特亚的讹人说法，**所以不是没有证据说站长**。但是**站长没有出来澄清**，可能就会让很多路人有了这种印象，这是站长名誉受到影响的因素——对面说你有讹人嫌疑，还放证据出来了，你却不敢当面回应，我只能相信你有问题了（注意这是双方似乎还没有真正的对接过），当时我也是这么想的。然后站长到第二天才回应，还差点把巅峰扯进来了，巅峰在方舟极限视频里什么地位想必您也是知道的，然后巅峰的人放截图直接说觉得站长恶心，站长的名声肯定会下滑啊。最后说话还带一点地方口音（我不是地域黑，我有亲戚也是广东的人，但的确在其他地方不喜欢这口音的人很多）。站长路人风评本来是不错的，4月2日直播帮站长说话的人也不少，但**当晚没回应是非常非常大的错误**，导致4月3日直播间觉得站长不是好人的声音多了起来。你可以说站长没有讹人的想法，但不可否认的是，内鬼肯定有这种想法，也是这么实践的。

你关注了直播就会知道，卡特亚直播中的主题一直不是您所谓的让站长承认是在讹他，而是站长给别人带来了大主播仗势欺人的印象，而这一点是莫须有的，如果被这样抹黑，再加上当时事情原委并不明朗，公开要服务器资金援助的时间点（之前一直只是在站内挂了二维码）又刚好那么完美，卡特亚看见“请捐款”肯定也很不舒服，所以会产生在讹他的感受。而且如果看了昨晚的直播，卡特亚也没说什么讹钱的事情，双方都认同内鬼很有问题。最后的分歧就在于卡特亚认为站长挂人不对，引爆了舆论，觉得站长对这方面要负责，还有到底站长有没有做错的地方。**最后站长一直都在说内鬼，说挂人帖出来的时候为什么不私聊**，没明白自己哪方面有做得不妥当的地方，卡特亚觉得站长一直在推卸责任，所以说站长是白莲花。路人观感自然是什么锅都让内鬼背，站长的风评就又降低了。不过卡特亚如果能为最开始的讹人言论道歉就更好了，但这样我觉得卡特亚做的就太绝了，站长就真的没台阶下了。但是我觉得站长是真的有些地方没明白，所以指出了我觉得站长不妥当的两点。

综上所述，我对您认为的**卡特亚的直播目的是让站长承认是在讹他**以及**他没有证据骂站长两天可以，站长不指明发事实不行**的言论不赞同。

**Comment by winrey** [comment]
@sxyugao 
我觉得您说的有一定的道理，确实是卡特亚粉丝的视角。如果我在您的位置，我也会做相同的判断。

**卡特亚就是要站长承认站长是在讹他。**

否则就得解释我更新中提出的证据——卡特亚口中的**“套人设”**  **“白莲花”**是什么意思，是为什么要提这些。

而`卡特亚:如果你不承认你有攻击我的动机，那么我们今天的谈话结束了`这又是什么意思。

_（就算是攻击，也最多是被侵权联系无果的反击吧？）_

不过卡特亚确实“有证据”，但是你也承认了，那些证据是“内鬼”在运营群里发的断章取义的“证据”，对吧。那么站长让卡特亚`承认是受到内鬼的影响，导致对他（站长）有偏见`，而卡特亚拒绝承认这点又是为什么？是不是说明卡特亚对有偏见？那么你有没有仔细想过，**这个偏见指的是是什么偏见**

顺带“当晚没回应是非常非常大的错误”这一点。。我猜测你是JZU的大学生。。如果你曾经受过996的毒打，你就会明白，工作一天是非常累的。通勤回家、吃饭还需要时间。站长这次准备充分之后，还是被带偏了节奏。很难想象当天精疲力尽，毫无准备，且没有NGA声援的站长会变成什么样。站长出面情况真的不一定会更好。

而且你也看到了，我认可你、站长和卡特亚心底的善良。其实卡特亚受到蒙蔽判断错误很正常。道个歉就可以了，多大点事啊。但是他不想道歉，这样就没办法GE了。现在的TE至少没有让kkdy关站，没有让kty糊掉，也应该没有影响站长的生活（大概吧）。就这样吧。

**Comment by sxyugao** [comment]
@winrey 的确，所以我提到了**不过卡特亚如果能为最开始的讹人言论道歉就更好了**。但是一直强调要私聊，说怕QQ被爆破而不是直接说**累了希望明天再聊**，这实在是让路人容易起疑，因为私聊在当时的那个语境在别人眼里可以说是理亏了的表现，也是站长风评下降很重要的原因，我当时都也是这么想的。你说的没错，卡特亚的确是一个很容易情绪化的人，经过前2天的事态发酵，可以说是很生气了，然后平时套人设，白莲花的人见多了，想当然的认为站长也是这样的人，**这种”以前我遇到的人......，所以以后我遇到的人也不可信，怕不是也是......“的思维的确是卡特亚的错误**，可能真的是经历了太多，4月2日晚他自曝生涯中的一些事让我感触很深，经常要以别人是不是想弄垮我来揣测其他人，真的是非常可悲的一件事。双方一开始的沟通实在是太差了，被内鬼耍得团团转。

你说站长一直在和卡特亚的运营主管沟通，**就目前的情况**是内鬼传达了非常夸大的要求，开口就是”请捐款“，想要入住运营群，卡特亚方面拒绝了，然后也没有继续沟通下去联系商务QQ，主要这里可能是站长被内鬼忽悠了，觉得沟通无果，不可能通过正常手段解决了，内鬼再提议要不要挂他，站长没细想就答应了。双方其实都没有体谅对方，站长工作一天非常累，通勤回家、吃饭还需要时间，卡特亚没有体谅站长；卡特亚正在直播，站长急性子直接挂人，站长也没有体谅卡特亚。

只能说**内鬼真的恶心**，本来可以双赢的一定要搅成两败俱伤，两边谁都亏，结果内鬼直接删好友跑路，啥事没有。真的希望社会上这种人能少一些。这种其实才是卡特亚最讨厌的人，**由内鬼的人品来揣测站长的人品，的确是卡特亚的错误**。最后卡特亚直播间里弹幕都是站长不是什么好人，站长真的也是百口莫辩了，说实话最后卡特亚名声臭了，站长名声也臭了，就没人管内鬼，最最最讨厌的人却没人骂。

**内鬼Biss**

P.S. 高中生一枚哦，学长曾就读的那种大学也是憧憬的呀

**Comment by winrey** [comment]
加油吧ww

<del>顺我校不值得</del>
