### ISSUE TITLE
筛选界面的小问题

### ISSUE THREAD

**Issue by Lim9er** [odex21/ArknightsData#27]
选中任何一个筛选条件时，将鼠标移动到还没归位的干员头像上会出现奇怪的显示效果；
在 iPad Air 3 横屏显示的情况下，点击每一行末的干员头像，伸出的小按钮会将该干员头像挤到另外一行；
（另外您写的这个资料站真的是太棒了，大四狗自愧不如

**Comment by odex21** [comment]
等接下来重构的时候，看看能不能优化下。
