### ISSUE TITLE
能不能不要更新就弹框

### ISSUE THREAD

**Issue by Aine-Linz** [odex21/ArknightsData#29]
请自动执行更新，或者自动刷新，不要老是弹那个框

**Comment by odex21** [comment]
主要是怕，如果有Bug，但是没及时更新，或者版本不对的话。会造成错误信息的传播。
小程序也差不多这样的。
不过，因为小程序不会打开多个Tag，所以可以不弹，每次自动更新。
不过现在引入数据库之后，除非前端有bug，一般不会弹了
