### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sxyugao** [odex21/ArknightsData#4]
排列组合中依次点职业标签有惊喜，在点到最后一个时会清空标签选择

**Comment by odex21** [comment]
点到最后一个就是所有筛选选项都选了
也就是等于没有筛选
例如星级选1，2，3，4，5，6

**Comment by sxyugao** [comment]
那为什么把按钮的选中边框保留？ui交互就是给人bug的感觉

**Comment by odex21** [comment]
> 那为什么把按钮的选中边框保留？ui交互就是给人bug的感觉

-觉得是Bug么。。。
边框保留，这是Button从选中状态到非选中状态后，保留的按钮选中状态。
点选星级 1 ， 然后取消  1 ，也是这个效果。

**Comment by sxyugao** [comment]
> -觉得是Bug么。。。
> 边框保留，这是Button从选中状态到非选中状态后，保留的按钮选中状态。
> 点选星级 1 ， 然后取消 1 ，也是这个效果。

那直接点清空就没有这个状态？？

**Comment by odex21** [comment]
> > -觉得是Bug么。。。
> > 边框保留，这是Button从选中状态到非选中状态后，保留的按钮选中状态。
> > 点选星级 1 ， 然后取消 1 ，也是这个效果。
> 
> 那直接点清空就没有这个状态？？

直接点清空，点击的是清空的按钮。清空按钮，也就是筛选组的名字，有选和没选都是默认样式。

而筛选的按钮，没选是plain样式，选了是默认的。

https://element.eleme.cn/#/zh-CN/component/button
这是介绍。

也不是不能覆盖掉，点按Plain Button 后样式。
只是现在这个样子，还有个提醒刚刚取消掉哪个按钮的作用。

**Comment by sxyugao** [comment]
以前没接触过过 vue，感觉控件被点击后会追加 :focus ，我只会比较笨的办法，感觉用 !important 强制覆盖 :focus 的样式就行了？
