### ISSUE TITLE
为什么没有添加皮肤

### ISSUE THREAD

**Issue by feilongproject** [odex21/ArknightsData#6]
为什么现在还不能显示皮肤啊，是遇到什么技术难题了吗

如果不是的话想要皮肤解包就行了，懒的话我这就有一份

**Comment by odex21** [comment]
有皮肤的。
但是没有单拎出来，做一个页面。
这是国庆那会加的。
在每个干员的立绘里，如果有皮肤的话，那就会显示皮肤出来。

等确定好资料站新名字之后，会开始加一些新功能
