### ISSUE TITLE
更新过后关卡敌人数据不显示。

### ISSUE THREAD

**Issue by xiaoshu-lin** [odex21/ArknightsData#9]
浏览器 Chrome 79.0.3945.117
用console简单看了一下，map-wrapper的最大长度不够大，右边的内容显示不出来。

**Comment by odex21** [comment]
能截图看看么
手机还是电脑

**Comment by xiaoshu-lin** [comment]
@odex21 
![image](https://user-images.githubusercontent.com/7893343/72833190-4445c800-3cc1-11ea-9457-7d1408dda0ea.png)
电脑端

**Comment by odex21** [comment]
好了。
grid 格子没对1900px以上的做处理。
